use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::domain::shared::{aggregate_root::EventQueue, errors::DomainError};
use crate::domain::exam_management::{
    entities::{Question, QuestionId},
    events::BankEvent,
    value_objects::OutcomeCode,
};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuestionBankId(pub Uuid);

impl QuestionBankId {
    pub fn new() -> Self { Self(Uuid::new_v4()) }
}

impl Default for QuestionBankId {
    fn default() -> Self { Self::new() }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DifficultyLevel { Easy, Medium, Hard }

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum QuestionSource { Manual, ImportedFromExam, AutoGenerated }

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionMetadata {
    pub tags:            Vec<String>,
    pub difficulty_hint: DifficultyLevel,
    pub source:          QuestionSource,
    pub created_at:      DateTime<Utc>,
}

impl Default for QuestionMetadata {
    fn default() -> Self {
        Self {
            tags:            vec![],
            difficulty_hint: DifficultyLevel::Medium,
            source:          QuestionSource::Manual,
            created_at:      Utc::now(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BankedQuestion {
    pub question: Question,
    pub metadata: QuestionMetadata,
}

impl BankedQuestion {
    pub fn new(question: Question) -> Self {
        Self { question, metadata: QuestionMetadata::default() }
    }
}

/// School-wide reusable question pool.
/// Questions live here and are *referenced* (not copied) by exams.
#[derive(Debug, Serialize, Deserialize)]
pub struct QuestionBank {
    pub id:        QuestionBankId,
    pub name:      String,
    pub questions: Vec<BankedQuestion>,
    #[serde(skip)]
    events: EventQueue<BankEvent>,
}

impl QuestionBank {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id:        QuestionBankId::new(),
            name:      name.into(),
            questions: vec![],
            events:    EventQueue::default(),
        }
    }

    pub fn id(&self) -> &QuestionBankId { &self.id }

    pub fn add_question(&mut self, question: Question) -> Result<&QuestionId, DomainError> {
        let id = question.id().clone();
        if self.questions.iter().any(|bq| bq.question.id() == &id) {
            return Err(DomainError::InvariantViolation(
                format!("Question {id} already exists in the bank"),
            ));
        }
        self.events.push(BankEvent::QuestionAdded {
            bank_id:       self.id.clone(),
            question_id:   id.clone(),
            question_type: question.question_type_label(),
        });
        self.questions.push(BankedQuestion::new(question));
        Ok(self.questions.last().map(|bq| bq.question.id()).unwrap())
    }

    pub fn remove_question(&mut self, id: &QuestionId) -> Result<BankedQuestion, DomainError> {
        let pos = self
            .questions
            .iter()
            .position(|bq| bq.question.id() == id)
            .ok_or_else(|| DomainError::NotFound {
                entity: "Question",
                id:     id.to_string(),
            })?;
        let removed = self.questions.remove(pos);
        self.events.push(BankEvent::QuestionRemoved {
            bank_id:     self.id.clone(),
            question_id: id.clone(),
        });
        Ok(removed)
    }

    pub fn find(&self, id: &QuestionId) -> Option<&BankedQuestion> {
        self.questions.iter().find(|bq| bq.question.id() == id)
    }

    pub fn find_mut(&mut self, id: &QuestionId) -> Option<&mut BankedQuestion> {
        self.questions.iter_mut().find(|bq| bq.question.id() == id)
    }

    pub fn filter_by_outcome(&self, outcome: &OutcomeCode) -> Vec<&BankedQuestion> {
        self.questions
            .iter()
            .filter(|bq| bq.question.outcomes().contains(outcome))
            .collect()
    }

    pub fn filter_by_score_range(&self, min: f32, max: f32) -> Vec<&BankedQuestion> {
        self.questions
            .iter()
            .filter(|bq| {
                let s = bq.question.stats().performance_score;
                s >= min && s <= max
            })
            .collect()
    }

    pub fn drain_events(&mut self) -> Vec<BankEvent> {
        self.events.drain()
    }
}
