[package]
name    = "tayan-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tayan-core     = { workspace = true }
tayan-compiler = { workspace = true }
tayan-db       = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
anyhow         = { workspace = true }
tokio          = { workspace = true }
tauri          = { workspace = true }
uuid           = { workspace = true }
sqlx           = { workspace = true }
chrono         = { workspace = true }
base64         = "0.22"
dirs-next      = { version = "2" }
ureq = { version = "2", features = ["json"] }
tar = "0.4"
flate2 = "1"
sha2 = "0.10"

[build-dependencies]
tauri-build = { workspace = true }
