[package]
name    = "tayan-db"
version.workspace = true
edition.workspace = true

[dependencies]
tayan-core = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }
chrono     = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
tokio      = { workspace = true }
sqlx       = { workspace = true }

[dev-dependencies]
dirs-next = "2"
