[package]
name    = "tayan-core"
version.workspace = true
edition.workspace = true

[dependencies]
tayan-macros = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
toml         = { workspace = true }
uuid         = { workspace = true }
chrono       = { workspace = true }
thiserror    = { workspace = true }
anyhow       = { workspace = true }
